spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: '${custom.dev_db_url}'
    username: '${custom.prod_db_username}'
    password: '${custom.prod_db_password}'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

custom:
  site:
    baseUrl: 3.35.136.175
