spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:  '${custom.dev_db_url}'
    username: '${custom.dev_db_username}'
    password: '${custom.dev_db_password}'
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
custom:
  site:
    baseUrl: 'localhost'